export type IconSize = "compact" | "regular" | "action" | "hero";
export type BrandColorMode = "inherit" | "brand";
export type IconName =
  | "home"
  | "about"
  | "experience"
  | "skills"
  | "certifications"
  | "education"
  | "projects"
  | "contact"
  | "cloud"
  | "observability"
  | "cicd"
  | "automation"
  | "networking"
  | "security"
  | "reliability"
  | "resilience"
  | "infrastructure"
  | "database"
  | "leadership"
  | "download"
  | "external-link"
  | "location"
  | "calendar"
  | "github"
  | "linkedin"
  | "email"
  | "certificate"
  | "containers";
export type BrandName =
  | "kubernetes"
  | "terraform"
  | "docker"
  | "github"
  | "gitlab"
  | "jenkins"
  | "datadog"
  | "prometheus"
  | "grafana"
  | "linux"
  | "nextjs"
  | "typescript"
  | "tailwind";
export type TechnologyName = BrandName | "aws" | "rancher" | "cloudwatch" | "elk";
